import { atom } from "nanostores";

export const globalState = atom([
  {
    "Discord-Username": "camden1",
    Elo: 828,
    L: 23,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/%E2%98%A5-NA1",
    "Riot-ID": "☥ #NA1",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Karthus, Lillia, Skarner",
    W: 26,
  },
  {
    "Discord-Username": "Illiumn",
    Elo: 722,
    L: 33,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/%E2%98%A5-NA1",
    "Riot-ID": "maneater#uwu",
    "S14S1-Rank": "Diamond",
    Team: "all",
    "Top-Champs": "Janna, Lux, Lulu",
    W: 19,
  },
  {
    "Discord-Username": "Jinlo",
    Elo: 865,
    L: 5,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/%E2%98%A5-NA1",
    "Riot-ID": "Jinlo#FWC",
    "S14S1-Rank": "Diamond",
    Team: "all",
    "Top-Champs": "Azir, Hwei, Xerath",
    W: 10,
  },
  {
    "Discord-Username": "crazychocolate1",
    Elo: 916,
    L: 27,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Yuanel-LOL",
    "Riot-ID": "Yuanel#LOL",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Briar, Hecarim, Kindred",
    W: 45,
  },
  {
    "Discord-Username": "originalwalrus",
    Elo: 812,
    L: 46,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/originalwalrus-NA1",
    "Riot-ID": "originalwalrus#na1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Ezreal, Lucian, Jhin",
    W: 30,
  },
  {
    "Discord-Username": "Doom Lion",
    Elo: 722,
    L: 18,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Doom%20Lion-NA1",
    "Riot-ID": "Doom Lion#NA1",
    "S14S1-Rank": "Platinum 4",
    Team: "all",
    "Top-Champs": "Maokai, Ornn, Chogath",
    W: 12,
  },
  {
    "Discord-Username": "iCuriozity",
    Elo: 795,
    L: 18,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/iCuriozity-NA1",
    "Riot-ID": "iCuriozity#na1",
    "S14S1-Rank": "Emerald 4",
    Team: "all",
    "Top-Champs": "Aphelios, Jhin, Ezreal",
    W: 14,
  },
  {
    "Discord-Username": "haitani.g",
    Elo: 820,
    L: 2,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/haitani-nikki",
    "Riot-ID": "haitani#nikki",
    "S14S1-Rank": "Master",
    Team: "DQ",
    "Top-Champs": "Taliyah, Lillia, Graves",
    W: 3,
  },
  {
    "Discord-Username": "Frosty",
    Elo: 753,
    L: 7,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Frosty6-NA1",
    "Riot-ID": "Frosty6#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Taliyah, Kaisa, Lissandra",
    W: 3,
  },
  {
    "Discord-Username": "HEADeyes7n31",
    Elo: 797,
    L: 51,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/HeadEyes7n31-NA1",
    "Riot-ID": "HEADeyes7n31#na1",
    "S14S1-Rank": "Platinum 3",
    Team: "all",
    "Top-Champs": "Poppy, Soraka, Karma",
    W: 45,
  },
  {
    "Discord-Username": "torquil0744",
    Elo: 846,
    L: 23,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/xXTORQUILXx-NA1",
    "Riot-ID": "xXTORQUILXx#NA1",
    "S14S1-Rank": "Diamond 3",
    Team: "all",
    "Top-Champs": "Karma, Rakan, Seraphine",
    W: 34,
  },
  {
    "Discord-Username": "Baraban",
    Elo: 801,
    L: 34,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Barry-GAP/champions",
    "Riot-ID": "Barry#gap",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Aatrox, Sett, Urgot",
    W: 30,
  },
  {
    "Discord-Username": "C4RNAGE",
    Elo: 777,
    L: 12,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/BCH%20LEGIXN-DRVEN",
    "Riot-ID": "BCH LEGIXN#DRVEN",
    "S14S1-Rank": "Gold 4",
    Team: "all",
    "Top-Champs": "Draven, Aphelios, Pyke",
    W: 10,
  },
  {
    "Discord-Username": "Toshiro Uzumaki#na1",
    Elo: 719,
    L: 14,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Toshiro%20Uzumaki-NA1",
    "Riot-ID": "Toshiro Uzumaki#na1",
    "S14S1-Rank": "Platinum 4",
    Team: "all",
    "Top-Champs": "Zac, Caitlyn, Jhin",
    W: 6,
  },
  {
    "Discord-Username": "Frischyy",
    Elo: 884,
    L: 52,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Frischy-4160",
    "Riot-ID": "Frischy#4160",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Amumu, Malphite, Brand",
    W: 55,
  },
  {
    "Discord-Username": "holstro",
    Elo: 782,
    L: 54,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/Holstro-NA1",
    "Riot-ID": "Holstro#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Thresh, Milio, Maokai",
    W: 46,
  },
  {
    "Discord-Username": "aaronomnicide",
    Elo: 735,
    L: 21,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/AaronOmni-NA1",
    "Riot-ID": "AaronOmni#NA1",
    "S14S1-Rank": "Emerald 3",
    Team: "all",
    "Top-Champs": "Mordekaiser, Camille, Sett",
    W: 13,
  },
  {
    "Discord-Username": "damnrightmoniker",
    Elo: 834,
    L: 19,
    "Main-Role": "Top",
    OPGG: "Bruh https://www.op.gg/summoners/na/Moniker-Gone",
    "Riot-ID": "Moniker#Gone",
    "S14S1-Rank": "Emerald 4",
    Team: "all",
    "Top-Champs": "KSante, Aatrox, Zeri",
    W: 24,
  },
  {
    "Discord-Username": "suwoop1234#qwer",
    Elo: 784,
    L: 3,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/multisearch/na?summoners=suwoop1234%23qwer",
    "Riot-ID": "suwoop1234#qwer",
    "S14S1-Rank": "Platinum 4",
    Team: "DQ",
    "Top-Champs": "Teemo, Jhin, Gragas",
    W: 2,
  },
  {
    "Discord-Username": "Shiisha",
    Elo: 807,
    L: 29,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Shiisha-NA1",
    "Riot-ID": "Shiisha#NA1",
    "S14S1-Rank": "Platinum 2",
    Team: "all",
    "Top-Champs": "Mordekaiser, Darius, Camille",
    W: 33,
  },
  {
    "Discord-Username": "comix1",
    Elo: 800,
    L: 1,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/NA/comix-0001",
    "Riot-ID": "comix#0001",
    "S14S1-Rank": "Diamond 3",
    Team: "DQ",
    "Top-Champs": "Camille, Riven, Gwen",
    W: 1,
  },
  {
    "Discord-Username": "thehumanfaith",
    Elo: 901,
    L: 6,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/TheHumanFaith-bruh?hl=ru_RU",
    "Riot-ID": "TheHumanFaith#bruh",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Camille, Akshan, Tryndamere",
    W: 17,
  },
  {
    "Discord-Username": "benz222555",
    Elo: 933,
    L: 7,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/ChillSavior-NA1",
    "Riot-ID": "ChillSavior#NA1",
    "S14S1-Rank": "Diamond 2",
    Team: "all",
    "Top-Champs": "RekSai, Udyr, Elise",
    W: 20,
  },
  {
    "Discord-Username": "lucifuge3001",
    Elo: 709,
    L: 59,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Lucifuge%20II-NA1",
    "Riot-ID": "Lucifuge II#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Mordekaiser, Shen, Illaoi",
    W: 46,
  },
  {
    "Discord-Username": "._stove",
    Elo: 851,
    L: 10,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Dragon%20Stormz-NA1",
    "Riot-ID": "Dragon Stormz#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Shaco, Kindred, Amumu",
    W: 15,
  },
  {
    "Discord-Username": "Salmemon",
    Elo: 839,
    L: 10,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/Okkotsu%20Yuta-NA1",
    "Riot-ID": "Okkotsu Yuta #na1",
    "S14S1-Rank": "Platinum 3",
    Team: "all",
    "Top-Champs": "Thresh, Renata, Braum",
    W: 15,
  },
  {
    "Discord-Username": "realmemesta",
    Elo: 799,
    L: 5,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Memesta-NA2 and https://www.op.gg/summoners/na/ModernDaytragedy-NA1",
    "Riot-ID": "Memesta#na2",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Karthus, Hecarim, Brand",
    W: 5,
  },
  {
    "Discord-Username": "mafia6117",
    Elo: 791,
    L: 41,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/%EB%A3%A8%EB%AF%B8%EB%84%88%EC%8A%A4-123",
    "Riot-ID": "루미너스#123",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Zed, Yone, Irelia",
    W: 34,
  },
  {
    "Discord-Username": "Alsomhi",
    Elo: 958,
    L: 19,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Y3meni-NA1",
    "Riot-ID": "Y3meni#na1",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "KSante, Zac, Urgot",
    W: 40,
  },
  {
    "Discord-Username": "n0me",
    Elo: 835,
    L: 4,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/N0ME-NA1",
    "Riot-ID": "n0me#na1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Janna, Hwei, Shaco",
    W: 7,
  },
  {
    "Discord-Username": "NateBev#8714",
    Elo: 770,
    L: 3,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/multisearch/na?summoners=natebev%23na1%2C%20natebev%23na2%2C%20natebev%23na3",
    "Riot-ID": "NateBev#NA3",
    "S14S1-Rank": "Diamond 2",
    Team: "DQ",
    "Top-Champs": "Diana, Draven, Xerath",
    W: 1,
  },
  {
    "Discord-Username": "Nachoreformed",
    Elo: 792,
    L: 10,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Nacho-NA69",
    "Riot-ID": "Nacho#NA69",
    "S14S1-Rank": "Diamond 3",
    Team: "all",
    "Top-Champs": "Garen, Pantheon, Darius",
    W: 11,
  },
  {
    "Discord-Username": "Mcfasho",
    Elo: 798,
    L: 8,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/MCFasho-NA1",
    "Riot-ID": "Mcfasho#na1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "JarvanIV, LeeSin, Hecarim",
    W: 9,
  },
  {
    "Discord-Username": "runo999",
    Elo: 746,
    L: 17,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/multisearch/na?summoners=stacking+hubris%23stack",
    "Riot-ID": "stacking hubris#stack",
    "S14S1-Rank": "Diamond 3",
    Team: "all",
    "Top-Champs": "Khazix, Evelynn, Brand",
    W: 13,
  },
  {
    "Discord-Username": "Fw.Hashem",
    Elo: 815,
    L: 25,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/RulersDesciple-RULER",
    "Riot-ID": "RulersDesciple#RULER",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Yasuo, AurelionSol, Smolder",
    W: 22,
  },
  {
    "Discord-Username": "lolspork",
    Elo: 801,
    L: 4,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Spork-USLD",
    "Riot-ID": "Spork#USLD",
    "S14S1-Rank": "Master",
    Team: "DQ",
    "Top-Champs": "Ryze, Zoe, Sylas",
    W: 4,
  },
  {
    "Discord-Username": "TrickeryZ_",
    Elo: 725,
    L: 13,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/TrickyZ-Supp",
    "Riot-ID": "Trickyz#Supp",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Thresh, Blitzcrank, Bard",
    W: 9,
  },
  {
    "Discord-Username": "madmantisgaming",
    Elo: 816,
    L: 99,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/LCSorHomeless-NA1",
    "Riot-ID": "LCSorHomeless-NA1",
    "S14S1-Rank": "Diamond 2",
    Team: "all",
    "Top-Champs": "Karma, Blitzcrank, Nami",
    W: 104,
  },
  {
    "Discord-Username": "RitzyEel",
    Elo: 889,
    L: 17,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/RitzyEel-NA1",
    "Riot-ID": "RitzyEel#NA1",
    "S14S1-Rank": "Diamond 1",
    Team: "all",
    "Top-Champs": "Kindred, Taliyah, Belveth",
    W: 21,
  },
  {
    "Discord-Username": "SuperSorry",
    Elo: 972,
    L: 3,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/SuperSorry-GRAVE",
    "Riot-ID": "SuperSorry#GRAVE",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Graves, Taliyah, Karthus",
    W: 8,
  },
  {
    "Discord-Username": "80887__",
    Elo: 853,
    L: 4,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/DarKCoS-NA1",
    "Riot-ID": "DarKCoS#NA1",
    "S14S1-Rank": "Diamond 1",
    Team: "all",
    "Top-Champs": "Lux, Katarina, Zoe",
    W: 8,
  },
  {
    "Discord-Username": "Cole",
    Elo: 784,
    L: 25,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/cole-6ft2",
    "Riot-ID": "cole#6ft2",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Draven, Taliyah, Jinx",
    W: 25,
  },
  {
    "Discord-Username": "shamal",
    Elo: 991,
    L: 16,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/Sasha%20Smalls-777",
    "Riot-ID": "Sasha Smalls #777",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Tristana, Twitch, Vayne",
    W: 39,
  },
  {
    "Discord-Username": "lostzero_",
    Elo: 946,
    L: 10,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/LostZeroツ-000",
    "Riot-ID": "LostZeroツ#000",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Jhin, Lucian, Jinx",
    W: 31,
  },
  {
    "Discord-Username": "Bladehell",
    Elo: 839,
    L: 22,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Blade-0005",
    "Riot-ID": "Blade#0005",
    "S14S1-Rank": "Emerald 1",
    Team: "all",
    "Top-Champs": "Akali, Yone, Yasuo",
    W: 25,
  },
  {
    "Discord-Username": "thebrehm",
    Elo: 833,
    L: 29,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Age%20Of%20The%20Cage-Custm",
    "Riot-ID": "Age Of The Cage#Custm",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Cassiopeia, Veigar, Xerath",
    W: 32,
  },
  {
    "Discord-Username": "exskull",
    Elo: 775,
    L: 6,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/ExSkull-NA1",
    "Riot-ID": "exskull#na1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Seraphine, Soraka, Lulu",
    W: 4,
  },
  {
    "Discord-Username": "jinjas1",
    Elo: 865,
    L: 5,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Jinlo-FWC",
    "Riot-ID": "Jinlo#FWC",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Azir, Sylas, Hwei",
    W: 10,
  },
  {
    "Discord-Username": "K1llum#NA1",
    Elo: 689,
    L: 17,
    "Main-Role": "Mid",
    OPGG: "https://u.gg/lol/profile/na1/k1llum-na1/overview",
    "Riot-ID": "K1llum#NA1",
    "S14S1-Rank": "Emerald 4",
    Team: "all",
    "Top-Champs": "Zed, Lux, Viktor",
    W: 6,
  },
  {
    "Discord-Username": "SCømm",
    Elo: 883,
    L: 7,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/SC%C3%B8mm-NA1",
    "Riot-ID": "SCømm#na1",
    "S14S1-Rank": "Emerald 4",
    Team: "all",
    "Top-Champs": "Caitlyn, Malzahar, Ashe",
    W: 15,
  },
  {
    "Discord-Username": "Sunnysins",
    Elo: 852,
    L: 54,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Hen%20Tai%20Oniisan-000",
    "Riot-ID": "Hen Tai Oniisan#000",
    "S14S1-Rank": "Emerald 1",
    Team: "all",
    "Top-Champs": "LeeSin, XinZhao, Smolder",
    W: 61,
  },
  {
    "Discord-Username": ".pizzaking",
    Elo: 778,
    L: 16,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Arbitrate-NA1",
    "Riot-ID": "Arbitrate#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Nocturne, Karthus, Hecarim",
    W: 13,
  },
  {
    "Discord-Username": "ShrubberyLol",
    Elo: 811,
    L: 19,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Shrubbery-00001",
    "Riot-ID": "shrubbery#00001",
    "S14S1-Rank": "Gold 3",
    Team: "all",
    "Top-Champs": "Azir, Hwei, Syndra",
    W: 18,
  },
  {
    "Discord-Username": "loveeatinghamburger",
    Elo: 777,
    L: 4,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/Catiasha-1928",
    "Riot-ID": "Catiasha #1928",
    "S14S1-Rank": "Emerald 4",
    Team: "DQ",
    "Top-Champs": "Thresh, Bard, Pyke",
    W: 2,
  },
  {
    "Discord-Username": "Jbthemaster",
    Elo: 821,
    L: 24,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/jbthemaster-NA1",
    "Riot-ID": "Jbthemaster#na1",
    "S14S1-Rank": "Emerald 3",
    Team: "all",
    "Top-Champs": "Vladimir, Illaoi, Hwei",
    W: 28,
  },
  {
    "Discord-Username": "jkuo9",
    Elo: 689,
    L: 19,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/Oh%20Look%20Twitch-NA1",
    "Riot-ID": "Oh Look Twitch#NA1",
    "S14S1-Rank": "Gold 4",
    Team: "DQ",
    "Top-Champs": "Twitch, Yone, Jinx",
    W: 7,
  },
  {
    "Discord-Username": "flametress",
    Elo: 769,
    L: 32,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Arch-Flame",
    "Riot-ID": "arch#flame",
    "S14S1-Rank": "Emerald 2",
    Team: "all",
    "Top-Champs": "Kennen, Diana, Nautilus",
    W: 30,
  },
  {
    "Discord-Username": "sir zzz",
    Elo: 751,
    L: 6,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/sir%20zzz-NA1",
    "Riot-ID": "sir zzz#NA1",
    "S14S1-Rank": "Emerald 2",
    Team: "DQ",
    "Top-Champs": "Zyra, Karma, Seraphine",
    W: 2,
  },
  {
    "Discord-Username": "Kruse",
    Elo: 829,
    L: 8,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/KruZ-CHRPZ",
    "Riot-ID": "KruZ#CHRPZ",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Hwei, Akshan, Azir",
    W: 11,
  },
  {
    "Discord-Username": "The Grack",
    Elo: 790,
    L: 10,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/The%20Grack-NA1",
    "Riot-ID": "The Grack#NA1",
    "S14S1-Rank": "Diamond 3",
    Team: "all",
    "Top-Champs": "Jhin, Xayah, Samira",
    W: 9,
  },
  {
    "Discord-Username": "MKhalifa",
    Elo: 803,
    L: 11,
    "Main-Role": "Bot",
    OPGG: "https://www.op.gg/summoners/na/Rulers%20Child-AAA",
    "Riot-ID": "Rulers Child#AAA",
    "S14S1-Rank": "Diamond 2",
    Team: "all",
    "Top-Champs": "Jinx, Ashe, Jhin",
    W: 12,
  },
  {
    "Discord-Username": "ttizzle",
    Elo: 836,
    L: 3,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/TTizzle830-NA1",
    "Riot-ID": "TTizzle830#NA1",
    "S14S1-Rank": "Master",
    Team: "DQ",
    "Top-Champs": "Zac, Nocturne, Thresh",
    W: 6,
  },
  {
    "Discord-Username": "ash3292",
    Elo: 734,
    L: 20,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/Ash-3292",
    "Riot-ID": "ash#3292",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "Milio, Jhin, Rell",
    W: 14,
  },
  {
    "Discord-Username": "drsava",
    Elo: 800,
    L: 11,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Sava-Doc",
    "Riot-ID": "Sava#Doc",
    "S14S1-Rank": "Diamond 2",
    Team: "all",
    "Top-Champs": "Jhin, Lux, Yone",
    W: 13,
  },
  {
    "Discord-Username": "c8h18_",
    Elo: 751,
    L: 13,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/Meshmellow-NA1",
    "Riot-ID": "Meshmellow#NA1",
    "S14S1-Rank": "Diamond 4",
    Team: "all",
    "Top-Champs": "MonkeyKing, Kayn, Udyr",
    W: 9,
  },
  {
    "Discord-Username": "Trevor",
    Elo: 866,
    L: 26,
    "Main-Role": "Mid",
    OPGG: "https://www.op.gg/summoners/na/Tissuebox-NA1",
    "Riot-ID": "Tissuebox#NA1",
    "S14S1-Rank": "Diamond 3",
    Team: "all",
    "Top-Champs": "TwistedFate, Veigar, Sona",
    W: 42,
  },
  {
    "Discord-Username": "Yepixel",
    Elo: 808,
    L: 13,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/Yepixel-NA1",
    "Riot-ID": "Yepixel#NA1",
    "S14S1-Rank": "Emerald 4",
    Team: "all",
    "Top-Champs": "Darius, Udyr, Garen",
    W: 14,
  },
  {
    "Discord-Username": "liamnoaholiver",
    Elo: 867,
    L: 46,
    "Main-Role": "Jungle",
    OPGG: "https://www.op.gg/summoners/na/The%20Mald-NA1",
    "Riot-ID": "The Mald#NA1",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Kayn, Graves, Karthus",
    W: 57,
  },
  {
    "Discord-Username": "Matarra",
    Elo: 833,
    L: 2,
    "Main-Role": "Top",
    OPGG: "https://u.gg/lol/profile/na1/matarra-sad/overview",
    "Riot-ID": "Matarra#sad",
    "S14S1-Rank": "Diamond 1",
    Team: "DQ",
    "Top-Champs": "Gangplank, Riven, Camille",
    W: 4,
  },
  {
    "Discord-Username": "fpsitachi",
    Elo: 767,
    L: 26,
    "Main-Role": "Top",
    OPGG: "https://www.op.gg/summoners/na/ItachiFPS-0001",
    "Riot-ID": "ItachiFPS#0001",
    "S14S1-Rank": "Platinum 3",
    Team: "all",
    "Top-Champs": "Darius, Aatrox, Garen",
    W: 16,
  },
  {
    "Discord-Username": "glompchu",
    Elo: 771,
    L: 8,
    "Main-Role": "Support",
    OPGG: "https://www.op.gg/summoners/na/Glomp%20Chu-o3o",
    "Riot-ID": "Glomp Chu#o3o",
    "S14S1-Rank": "Master",
    Team: "all",
    "Top-Champs": "Milio, Sona, Karma",
    W: 5,
  },
]);
